# Generated by Django 5.2.8 on 2025-11-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
