# Generated by Django 5.2.8 on 2025-11-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_task_options_remove_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='leader_of_course',
        ),
    ]
