# Generated by Django 5.2.8 on 2025-11-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_description_course_leader_of_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='leader_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
