# Generated by Django 5.2.8 on 2025-11-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_leader_of_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='leader_of_course',
            field=models.CharField(max_length=255),
        ),
    ]
